/**
 * TypeScript types for the GenERP platform.
 */

// ---------------------------------------------------------------------------
// Tenant
// ---------------------------------------------------------------------------

export interface Tenant {
  id: string;
  name: string;
  slug: string;
  plan: "free" | "pro" | "enterprise";
  industry: string;
  size: "1-10" | "11-50" | "51-200" | "200+";
  schema_name: string;
  is_active: boolean;
}

// ---------------------------------------------------------------------------
// ERP Schema
// ---------------------------------------------------------------------------

export type SQLType =
  | "uuid"
  | "text"
  | "integer"
  | "bigint"
  | "boolean"
  | "timestamp"
  | "timestamptz"
  | "date"
  | "jsonb"
  | `varchar(${number})`
  | `decimal(${number},${number})`
  | "text[]"
  | "uuid[]";

export interface ERPField {
  name: string;
  display_name: string;
  type: string;
  required: boolean;
  unique: boolean;
  default: string | null;
  description: string;
}

export interface ERPRelation {
  name: string;
  type: "many_to_one" | "one_to_many" | "many_to_many";
  target_entity: string;
  foreign_key: string;
  description: string;
}

export interface ERPEntity {
  name: string;
  display_name: string;
  description: string;
  category: "finance" | "crm" | "hr" | "supply_chain" | "general";
  fields: ERPField[];
  relations: ERPRelation[];
  indexes: string[];
  default_sort: string;
}

export interface ERPSchema {
  entities: ERPEntity[];
  business_context: string;
  suggested_workflows: string[];
}

// ---------------------------------------------------------------------------
// ERP Module (stored in DB)
// ---------------------------------------------------------------------------

export interface ERPModule {
  id: string;
  name: string;
  display_name: string;
  category: string;
  schema_definition: ERPSchema;
  ui_config: ModuleUIConfig;
  api_routes: Record<string, unknown>;
  is_active: boolean;
}

// ---------------------------------------------------------------------------
// UI Config (generated by UIAgent)
// ---------------------------------------------------------------------------

export type UIFieldType =
  | "text"
  | "number"
  | "currency"
  | "boolean"
  | "date"
  | "datetime"
  | "uuid"
  | "json";

export interface ColumnConfig {
  id: string;
  header: string;
  accessorKey: string;
  type: UIFieldType;
  sortable: boolean;
  filterable: boolean;
}

export interface TableAction {
  label: string;
  type: "create" | "edit" | "delete" | "custom";
  variant: "primary" | "secondary" | "destructive" | "ghost";
}

export interface FilterConfig {
  key: string;
  label: string;
  type: "text" | "select" | "date" | "boolean";
  options?: { label: string; value: string }[];
}

export interface PaginationConfig {
  pageSize: number;
  pageSizeOptions: number[];
}

export interface ListViewConfig {
  type: "data_table";
  title: string;
  columns: ColumnConfig[];
  actions: TableAction[];
  filters: FilterConfig[];
  pagination: PaginationConfig;
}

export interface FormConfig {
  type: "form";
  title: string;
  json_schema: Record<string, unknown>;
  ui_schema: Record<string, unknown>;
}

export interface DetailViewConfig {
  type: "detail";
  title: string;
  sections: Array<{
    title: string;
    fields: Array<{ key: string; label: string; type: UIFieldType }>;
  }>;
  tabs: Array<{ label: string; key: string }>;
  actions: TableAction[];
}

export interface MetricConfig {
  key: string;
  label: string;
  query: string;
  icon: string;
}

export interface ChartConfig {
  type: "bar" | "line" | "pie" | "area";
  title: string;
  x_key: string;
  y_key: string;
  data_query: string;
}

export interface DashboardConfig {
  type: "dashboard";
  title: string;
  metrics: MetricConfig[];
  charts: ChartConfig[];
}

export interface ModuleUIConfig {
  module_name: string;
  display_name: string;
  api_base: string;
  list_view: ListViewConfig;
  create_form: FormConfig;
  detail_view: DetailViewConfig;
  dashboard: DashboardConfig;
}

// ---------------------------------------------------------------------------
// Chat / SSE
// ---------------------------------------------------------------------------

export type SSEEventType =
  | "text"
  | "action"
  | "ui_update"
  | "meta"
  | "error"
  | "done";

export interface SSETextEvent {
  type: "text";
  content: string;
}

export interface SSEActionEvent {
  type: "action";
  action: string;
  data?: unknown;
  schema?: ERPSchema;
}

export interface SSEUIUpdateEvent {
  type: "ui_update";
  module: string;
  display_name: string;
  category: string;
  config: ModuleUIConfig;
}

export interface SSEMetaEvent {
  type: "meta";
  conversation_id: string;
}

export interface SSEErrorEvent {
  type: "error";
  message: string;
}

export interface SSEDoneEvent {
  type: "done";
}

export type SSEEvent =
  | SSETextEvent
  | SSEActionEvent
  | SSEUIUpdateEvent
  | SSEMetaEvent
  | SSEErrorEvent
  | SSEDoneEvent;

// ---------------------------------------------------------------------------
// Chat messages
// ---------------------------------------------------------------------------

export interface ChatMessage {
  id: string;
  role: "user" | "assistant";
  content: string;
  timestamp: Date;
  actions?: SSEActionEvent[];
}
